#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : R-clustMixType
Version  : 0.4.2
Release  : 64
URL      : https://cran.r-project.org/src/contrib/clustMixType_0.4-2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/clustMixType_0.4-2.tar.gz
Summary  : k-Prototypes Clustering for Mixed Variable-Type Data
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-RColorBrewer
Requires: R-combinat
Requires: R-dplyr
Requires: R-rlang
Requires: R-tibble
BuildRequires : R-RColorBrewer
BuildRequires : R-combinat
BuildRequires : R-dplyr
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Development version of the R Package clustMixType
<img src="man/figures/logo.png" align="right" height="139" />

%prep
%setup -q -n clustMixType
pushd ..
cp -a clustMixType buildavx2
popd
pushd ..
cp -a clustMixType buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719946648

%install
export SOURCE_DATE_EPOCH=1719946648
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/clustMixType/CITATION
/usr/lib64/R/library/clustMixType/DESCRIPTION
/usr/lib64/R/library/clustMixType/INDEX
/usr/lib64/R/library/clustMixType/Meta/Rd.rds
/usr/lib64/R/library/clustMixType/Meta/features.rds
/usr/lib64/R/library/clustMixType/Meta/hsearch.rds
/usr/lib64/R/library/clustMixType/Meta/links.rds
/usr/lib64/R/library/clustMixType/Meta/nsInfo.rds
/usr/lib64/R/library/clustMixType/Meta/package.rds
/usr/lib64/R/library/clustMixType/NAMESPACE
/usr/lib64/R/library/clustMixType/NEWS
/usr/lib64/R/library/clustMixType/R/clustMixType
/usr/lib64/R/library/clustMixType/R/clustMixType.rdb
/usr/lib64/R/library/clustMixType/R/clustMixType.rdx
/usr/lib64/R/library/clustMixType/help/AnIndex
/usr/lib64/R/library/clustMixType/help/aliases.rds
/usr/lib64/R/library/clustMixType/help/clustMixType.rdb
/usr/lib64/R/library/clustMixType/help/clustMixType.rdx
/usr/lib64/R/library/clustMixType/help/figures/logo.png
/usr/lib64/R/library/clustMixType/help/paths.rds
/usr/lib64/R/library/clustMixType/html/00Index.html
/usr/lib64/R/library/clustMixType/html/R.css
/usr/lib64/R/library/clustMixType/tests/testthat.R
/usr/lib64/R/library/clustMixType/tests/testthat/test_basics.R
/usr/lib64/R/library/clustMixType/tests/testthat/test_clustervalidation.R
